from abc import ABC
from abc import abstractmethod


from ai_provider.generation_request import GenerationRequest
from ai_provider.models import AIResponse


class AIProvider(ABC):
    """
    Base class for AI providers. Defines the interface for generating responses
    and streaming tokens from language models.
    """

    @abstractmethod
    async def generate(
        self,
        request: GenerationRequest | None = None,
    ) -> AIResponse:
        """
        Generate a response from an LLM based on the provided request.

        Args:
            request (GenerationRequest | None): An object containing the prompt
                and generation options. If None, default values may be used.

        Returns:
            AIResponse: The generated response from the LLM.
        """

    @abstractmethod
    async def stream(
        self,
        request: GenerationRequest | None = None,
    ):
        """
        Stream tokens from an LLM based on the provided request.

        Args:
            request (GenerationRequest | None): An object containing the prompt
                and generation options. If None, default values may be used.

        Yields:
            str: Each token generated by the LLM.
        """