"""Data structures for learned extraction strategies."""

from __future__ import annotations

from dataclasses import dataclass, field
from pathlib import Path
from typing import Any, Literal

from aip_canonica.models.document_type import DocumentType


@dataclass(slots=True)
class LearnedStrategy:
    """A learned, reusable extraction strategy for a document family."""

    name: str
    document_type: DocumentType
    anchor_keywords: list[str] = field(default_factory=list)
    table_header_keywords: list[str] = field(default_factory=list)
    column_mapping: dict[str, str] = field(default_factory=dict)
    metadata_fields: dict[str, str] = field(default_factory=dict)
    layout_type: Literal["flat_tabular", "multiline_block", "key_value_form"] = "flat_tabular"
    evolution_mode: Literal["create_new", "evolve_existing"] = "create_new"
    related_extractor_name: str | None = None
    block_delimiters: dict[str, str] = field(default_factory=dict)
    notes: str = ""

    def to_dict(self) -> dict[str, Any]:
        return {
            "name": self.name,
            "document_type": self.document_type.value,
            "anchor_keywords": self.anchor_keywords,
            "table_header_keywords": self.table_header_keywords,
            "column_mapping": self.column_mapping,
            "metadata_fields": self.metadata_fields,
            "layout_type": self.layout_type,
            "evolution_mode": self.evolution_mode,
            "related_extractor_name": self.related_extractor_name,
            "block_delimiters": self.block_delimiters,
            "notes": self.notes,
        }


@dataclass(slots=True)
class LearningReport:
    """Report generated by AI StrategyLearner when analyzing document layouts.

    Compares standard extractor metadata with layout-specific metadata discovered by AI
    to determine if creating a specialized extractor is warranted.
    """

    document_name: str
    detected_document_type: DocumentType
    baseline_fields_extracted: list[str] = field(default_factory=list)
    ai_discovered_fields: list[str] = field(default_factory=list)
    additional_metadata_fields: list[str] = field(default_factory=list)
    recommended_action: str = "use_generic"  # "create_specialized_extractor" | "use_generic"
    strategy: LearnedStrategy | None = None
    generated_code_snippet: str = ""
    extractor_file_path: Path | None = None
    report_file_path: Path | None = None
    notes: str = ""

    def summary(self) -> str:
        """Return a formatted developer-facing concise summary report with clickable file links."""
        lines = [
            f"=== Canonica Learning Report for '{self.document_name}' ===",
            f"Detected Document Type : {self.detected_document_type.value}",
            f"Standard Fields Found  : {', '.join(self.baseline_fields_extracted) or 'None'}",
            f"AI Discovered Fields   : {', '.join(self.ai_discovered_fields) or 'None'}",
            f"Richer Metadata Fields : {', '.join(self.additional_metadata_fields) or 'None (Generic extractor is sufficient)'}",
            f"Recommended Action     : {self.recommended_action.upper()}",
        ]
        if self.notes:
            lines.append(f"Layout Observations    : {self.notes}")
        if self.extractor_file_path:
            lines.append(f"Generated Extractor    : {self.extractor_file_path.as_uri()}")
        else:
            lines.append("Generated Extractor    : None")
        if self.report_file_path:
            lines.append(f"Detailed Report        : {self.report_file_path.as_uri()}")
        else:
            lines.append("Detailed Report        : None")
        lines.append("=" * 60)
        return "\n".join(lines)