"""Data structures for learned extraction strategies."""

from __future__ import annotations

from dataclasses import dataclass, field
from pathlib import Path
from typing import Any

from aip_canonica.models.document_type import DocumentType


@dataclass(slots=True)
class LearnedStrategy:
    """A learned, reusable extraction strategy for a document family.

    This class encapsulates the configuration required to extract structured data
    from documents of a specific type using a specialized strategy.
    """

    name: str
    """Human-readable name of the strategy, used for identification and logging."""

    document_type: DocumentType
    """The document type this strategy is designed for."""

    anchor_keywords: list[str] = field(default_factory=list)
    """Keywords used to identify sections or regions of interest in documents."""

    table_header_keywords: list[str] = field(default_factory=list)
    """Keywords used to detect table headers in documents."""

    column_mapping: dict[str, str] = field(default_factory=dict)
    """Mapping from document column names to standardized metadata field names."""

    metadata_fields: dict[str, str] = field(default_factory=dict)
    """Mapping from document metadata keys to standardized metadata field names."""

    notes: str = ""
    """Additional notes or observations about the strategy or document type."""

    def to_dict(self) -> dict[str, Any]:
        """Convert the strategy to a dictionary for serialization.

        Returns:
            A dictionary representation of the strategy with all fields.
        """
        return {
            "name": self.name,
            "document_type": self.document_type.value,
            "anchor_keywords": self.anchor_keywords,
            "table_header_keywords": self.table_header_keywords,
            "column_mapping": self.column_mapping,
            "metadata_fields": self.metadata_fields,
            "notes": self.notes,
        }


@dataclass(slots=True)
class LearningReport:
    """Report generated by AI StrategyLearner when analyzing document layouts.

    This report compares standard extractor metadata with layout-specific metadata
    discovered by AI to determine if creating a specialized extractor is warranted.
    """

    document_name: str
    """Name of the document analyzed to generate this report."""

    detected_document_type: DocumentType
    """Document type automatically detected by the AI during analysis."""

    baseline_fields_extracted: list[str] = field(default_factory=list)
    """Fields extracted using the generic, baseline extractor."""

    ai_discovered_fields: list[str] = field(default_factory=list)
    """Fields identified by AI as being present in the document layout."""

    additional_metadata_fields: list[str] = field(default_factory=list)
    """Additional metadata fields discovered by AI that are not part of the baseline."""

    recommended_action: str = "use_generic"
    """Recommended action based on the analysis. Possible values:
       - 'create_specialized_extractor' (if AI-discovered fields are significant)
       - 'use_generic' (if baseline extractor is sufficient)
    """

    strategy: LearnedStrategy | None = None
    """The learned strategy generated by the AI if a specialized extractor is recommended."""

    generated_code_snippet: str = ""
    """Sample code snippet generated by the AI for implementing the specialized extractor."""

    extractor_file_path: Path | None = None
    """File path to the generated extractor implementation, if any."""

    report_file_path: Path | None = None
    """File path to the detailed report generated by the AI, if any."""

    notes: str = ""
    """Additional observations or notes from the AI during analysis."""

    def summary(self) -> str:
        """Return a formatted developer-facing concise summary report with clickable file links.

        The summary includes key information about the document analysis, AI-discovered fields,
        and recommendations for whether a specialized extractor should be created.
        """
        lines = [
            f"=== Canonica Learning Report for '{self.document_name}' ===",
            f"Detected Document Type : {self.detected_document_type.value}",
            f"Standard Fields Found  : {', '.join(self.baseline_fields_extracted) or 'None'}",
            f"AI Discovered Fields   : {', '.join(self.ai_discovered_fields) or 'None'}",
            f"Richer Metadata Fields : {', '.join(self.additional_metadata_fields) or 'None (Generic extractor is sufficient)'}",
            f"Recommended Action     : {self.recommended_action.upper()}",
        ]
        if self.notes:
            lines.append(f"Layout Observations    : {self.notes}")
        if self.extractor_file_path:
            lines.append(f"Generated Extractor    : {self.extractor_file_path.as_uri()}")
        if self.report_file_path:
            lines.append(f"Detailed Report        : {self.report_file_path.as_uri()}")
        lines.append("=" * 60)
        return "\n".join(lines)