"""Data structures for learned extraction strategies."""

from __future__ import annotations

from dataclasses import dataclass, field
from pathlib import Path
from typing import Any

from aip_canonica.models.document_type import DocumentType


@dataclass(slots=True)
class LearnedStrategy:
    """A learned, reusable extraction strategy for a document family.

    Attributes:
        name: Name of the strategy.
        document_type: Type of document this strategy applies to.
        anchor_keywords: Keywords used to identify document sections.
        table_header_keywords: Keywords used to identify table headers.
        column_mapping: Mapping of document columns to metadata fields.
        metadata_fields: Custom metadata fields for document extraction.
        notes: Additional notes about the strategy.
    """

    name: str
    document_type: DocumentType
    anchor_keywords: list[str] = field(default_factory=list)
    table_header_keywords: list[str] = field(default_factory=list)
    column_mapping: dict[str, str] = field(default_factory=dict)
    metadata_fields: dict[str, str] = field(default_factory=dict)
    notes: str = ""

    def to_dict(self) -> dict[str, Any]:
        """Convert the strategy to a dictionary for serialization.

        Returns:
            A dictionary representation of the strategy with document_type converted
            to its string value.
        """
        return {
            "name": self.name,
            "document_type": self.document_type.value,
            "anchor_keywords": self.anchor_keywords,
            "table_header_keywords": self.table_header_keywords,
            "column_mapping": self.column_mapping,
            "metadata_fields": self.metadata_fields,
            "notes": self.notes,
        }


@dataclass(slots=True)
class LearningReport:
    """Report generated by AI StrategyLearner when analyzing document layouts.

    Compares standard extractor metadata with layout-specific metadata discovered by AI
    to determine if creating a specialized extractor is warranted.

    Attributes:
        document_name: Name of the document analyzed.
        detected_document_type: Document type detected by AI analysis.
        baseline_fields_extracted: Fields extracted using the standard extractor.
        ai_discovered_fields: Fields discovered by AI analysis.
        additional_metadata_fields: Additional metadata fields identified by AI.
        recommended_action: Action recommended based on analysis ("create_specialized_extractor" or "use_generic").
        strategy: Learned strategy if a specialized extractor is recommended.
        generated_code_snippet: Code snippet for the generated extractor.
        extractor_file_path: Path to the generated extractor file.
        report_file_path: Path to the detailed report file.
        notes: Additional notes from the analysis.
    """

    document_name: str
    detected_document_type: DocumentType
    baseline_fields_extracted: list[str] = field(default_factory=list)
    ai_discovered_fields: list[str] = field(default_factory=list)
    additional_metadata_fields: list[str] = field(default_factory=list)
    recommended_action: str = "use_generic"  # "create_specialized_extractor" | "use_generic"
    strategy: LearnedStrategy | None = None
    generated_code_snippet: str = ""
    extractor_file_path: Path | None = None
    report_file_path: Path | None = None
    notes: str = ""

    def summary(self) -> str:
        """Return a formatted developer-facing concise summary report with clickable file links."""
        lines = [
            f"=== Canonica Learning Report for '{self.document_name}' ===",
            f"Detected Document Type : {self.detected_document_type.value}",
            f"Standard Fields Found  : {', '.join(self.baseline_fields_extracted) or 'No standard fields found.'}",
            f"AI Discovered Fields   : {', '.join(self.ai_discovered_fields) or 'No AI-discovered fields found.'}",
            f"Richer Metadata Fields : {', '.join(self.additional_metadata_fields) or 'No additional metadata fields found. Generic extractor is sufficient.'}",
        ]

        if self.recommended_action == "use_generic":
            lines.append("Action Recommended: Use generic extractor.")
        else:
            lines.append("Action Recommended: Create specialized extractor.")

        if self.strategy:
            lines.append(f"Strategy: {self.strategy.name}")

        if self.extractor_file_path:
            lines.append(f"Extractor File: {self.extractor_file_path}")

        if self.report_file_path:
            lines.append(f"Report File: {self.report_file_path}")

        if self.notes:
            lines.append(f"Notes: {self.notes}")

        return "\n".join(lines)