from abc import ABC
from abc import abstractmethod
from typing import AsyncGenerator

from aip_provider.generation_request import GenerationRequest
from aip_provider.models import AIResponse


class AIProvider(ABC):
    """Abstract base class for AIP providers, defining the interface for generating responses and streaming tokens."""

    @abstractmethod
    async def generate(
        self,
        request: GenerationRequest | None = None,
    ) -> AIResponse:
        """
        Generate a response from an LLM based on the provided request.

        Args:
            request (GenerationRequest | None): The request containing the prompt and other parameters.
                If None, default parameters may be used.

        Returns:
            AIResponse: The generated response from the LLM.
        """

    @abstractmethod
    async def stream(
        self,
        request: GenerationRequest | None = None,
    ) -> AsyncGenerator[AIResponse, None]:
        """
        Stream tokens generated by the LLM based on the provided request.

        Args:
            request (GenerationRequest | None): The request containing the prompt and other parameters.
                If None, default parameters may be used.

        Yields:
            AIResponse: Each token or partial response generated by the LLM.
        """